platform:
- x64
environment:
  DEBUG: electron-windows-installer:*
  nodejs_version: "6"
  matrix:
  - node_installer: yarn
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
branches:
  only:
  - master

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g npm@4
- appveyor DownloadFile https://nightly.yarnpkg.com/yarn-0.19.0-20161210.1823-unsigned.msi
- msiexec /i yarn-0.19.0-20161210.1823-unsigned.msi /qn
- set PATH=%APPDATA%\npm;%PATH%
- npm install

test_script:
- node --version
- npm --version
- npm test -- --installer=%node_installer%

build: off
